import React from 'react';

// Font Awesome Icons
import {
  FaDocker,
  FaJenkins,
  FaGitlab,
  FaNodeJs,
  FaHome,
  FaCloud,
  FaDatabase,
  FaNetworkWired,
  FaLinux,
  FaPython,
  FaJava,
  FaPhp,
  FaJs,
  FaReact,
  FaServer,
  FaUbuntu,
  FaWindows,
  FaApple,
  FaRaspberryPi,
  FaCogs,
  FaLock,
  FaMusic,
  FaBook,
  FaGamepad,
  FaRegFileCode,
  FaRegQuestionCircle,
  FaRobot,
  FaChartLine,
  FaNewspaper,
  FaHtml5,
  FaGithub,
  FaAws,
  FaChartBar,
  FaSun,
  FaMoon,
  FaVolumeUp,
  FaVolumeMute,
  FaTachometerAlt
} from 'react-icons/fa';

// Simple Icons
import {
  SiJellyfin,
  SiNextcloud,
  SiMariadb,
  SiRedis,
  SiPihole,
  SiPortainer,
  SiHomeassistant,
  SiQbittorrent,
  SiWatchtower,
  SiDuckduckgo,
  SiVault,
  SiSonarr,
  SiRadarr,
  SiOpenai,
  SiAstro,
  SiDjango,
  SiFastapi,
  SiKubernetes,
  SiLangchain,
  SiMongodb,
  SiMysql,
  SiNextdotjs,
  SiOllama,
  SiPandas,
  SiPostgresql,
  SiPytorch,
  SiScikitlearn,
  SiStreamlit,
  SiTailwindcss,
  SiTensorflow,
  SiTypescript,
  SiUptimekuma,
  SiDrupal,
  SiGrafana
} from 'react-icons/si';

// Font Awesome 6 Icons
import {
  FaGithub as Fa6Github,
  FaLinkedin,
  FaXTwitter
} from 'react-icons/fa6';

// Re-export all icons
export {
  // Font Awesome Icons
  FaDocker,
  FaJenkins,
  FaGitlab,
  FaNodeJs,
  FaHome,
  FaCloud,
  FaDatabase,
  FaNetworkWired,
  FaLinux,
  FaPython,
  FaJava,
  FaPhp,
  FaJs,
  FaReact,
  FaServer,
  FaUbuntu,
  FaWindows,
  FaApple,
  FaRaspberryPi,
  FaCogs,
  FaLock,
  FaMusic,
  FaBook,
  FaGamepad,
  FaRegFileCode,
  FaRegQuestionCircle,
  FaRobot,
  FaChartLine,
  FaNewspaper,
  FaHtml5,
  FaGithub,
  FaAws,
  FaChartBar,
  FaSun,
  FaMoon,
  FaVolumeUp,
  FaVolumeMute,
  FaTachometerAlt,

  // Simple Icons
  SiJellyfin,
  SiNextcloud,
  SiMariadb,
  SiRedis,
  SiPihole,
  SiPortainer,
  SiHomeassistant,
  SiQbittorrent,
  SiWatchtower,
  SiDuckduckgo,
  SiVault,
  SiSonarr,
  SiRadarr,
  SiOpenai,
  SiAstro,
  SiDjango,
  SiFastapi,
  SiKubernetes,
  SiLangchain,
  SiMongodb,
  SiMysql,
  SiNextdotjs,
  SiOllama,
  SiPandas,
  SiPostgresql,
  SiPytorch,
  SiScikitlearn,
  SiStreamlit,
  SiTailwindcss,
  SiTensorflow,
  SiTypescript,
  SiUptimekuma,
  SiDrupal,
  SiGrafana,

  // Font Awesome 6 Icons
  Fa6Github,
  FaLinkedin,
  FaXTwitter
};

// Helper function to get icon data
export function getIconData(name: string) {
  const iconMap: Record<string, { icon: any, url: string, label: string }> = {
    // Technology Icons
    'python': { icon: FaPython, url: 'https://www.python.org/', label: 'Python' },
    'javascript': { icon: FaJs, url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript', label: 'JavaScript' },
    'typescript': { icon: SiTypescript, url: 'https://www.typescriptlang.org/', label: 'TypeScript' },
    'react': { icon: FaReact, url: 'https://react.dev/', label: 'React' },
    'next.js': { icon: SiNextdotjs, url: 'https://nextjs.org/', label: 'Next.js' },
    'nextjs': { icon: SiNextdotjs, url: 'https://nextjs.org/', label: 'Next.js' },
    'astro': { icon: SiAstro, url: 'https://astro.build/', label: 'Astro' },
    'node.js': { icon: FaNodeJs, url: 'https://nodejs.org/', label: 'Node.js' },
    'nodejs': { icon: FaNodeJs, url: 'https://nodejs.org/', label: 'Node.js' },
    'docker': { icon: FaDocker, url: 'https://www.docker.com/', label: 'Docker' },
    'kubernetes': { icon: SiKubernetes, url: 'https://kubernetes.io/', label: 'Kubernetes' },
    'linux': { icon: FaLinux, url: 'https://www.linux.org/', label: 'Linux' },
    'ci/cd': { icon: FaCogs, url: 'https://en.wikipedia.org/wiki/CI/CD', label: 'CI/CD' },
    'cicd': { icon: FaCogs, url: 'https://en.wikipedia.org/wiki/CI/CD', label: 'CI/CD' },
    'portainer': { icon: SiPortainer, url: 'https://www.portainer.io/', label: 'Portainer' },
    'nginx': { icon: FaServer, url: 'https://nginx.org/', label: 'Nginx' },
    'uptime kuma': { icon: SiUptimekuma, url: 'https://github.com/louislam/uptime-kuma', label: 'Uptime Kuma' },
    'uptime-kuma': { icon: SiUptimekuma, url: 'https://github.com/louislam/uptime-kuma', label: 'Uptime Kuma' },
    'tensorflow': { icon: SiTensorflow, url: 'https://www.tensorflow.org/', label: 'TensorFlow' },
    'pytorch': { icon: SiPytorch, url: 'https://pytorch.org/', label: 'PyTorch' },
    'nlp': { icon: FaRobot, url: 'https://en.wikipedia.org/wiki/Natural_language_processing', label: 'NLP' },
    'computer vision': { icon: FaRegFileCode, url: 'https://en.wikipedia.org/wiki/Computer_vision', label: 'Computer Vision' },
    'mlops': { icon: FaCogs, url: 'https://en.wikipedia.org/wiki/MLOps', label: 'MLOps' },
    'pandas': { icon: SiPandas, url: 'https://pandas.pydata.org/', label: 'Pandas' },
    'scikit-learn': { icon: SiScikitlearn, url: 'https://scikit-learn.org/', label: 'Scikit-learn' },
    'scikitlearn': { icon: SiScikitlearn, url: 'https://scikit-learn.org/', label: 'Scikit-learn' },
    'langchain': { icon: SiLangchain, url: 'https://www.langchain.com/', label: 'LangChain' },
    'ollama': { icon: SiOllama, url: 'https://ollama.com/', label: 'Ollama' },
    'aws': { icon: FaAws, url: 'https://aws.amazon.com/', label: 'AWS' },
    'gcp': { icon: FaCloud, url: 'https://cloud.google.com/', label: 'GCP' },
    'github actions': { icon: FaGithub, url: 'https://github.com/features/actions', label: 'GitHub Actions' },
    'github-actions': { icon: FaGithub, url: 'https://github.com/features/actions', label: 'GitHub Actions' },
    'watchtower': { icon: SiWatchtower, url: 'https://containrrr.dev/watchtower/', label: 'Watchtower' },
    'vaultwarden': { icon: SiVault, url: 'https://vaultwarden.dev/', label: 'Vaultwarden' },
    'html/css': { icon: FaHtml5, url: 'https://developer.mozilla.org/en-US/docs/Web/HTML', label: 'HTML/CSS' },
    'tailwind css': { icon: SiTailwindcss, url: 'https://tailwindcss.com/', label: 'Tailwind CSS' },
    'tailwindcss': { icon: SiTailwindcss, url: 'https://tailwindcss.com/', label: 'Tailwind CSS' },
    'tkinter': { icon: FaPython, url: 'https://wiki.python.org/moin/TkInter', label: 'Tkinter' },
    'django': { icon: SiDjango, url: 'https://www.djangoproject.com/', label: 'Django' },
    'fastapi': { icon: SiFastapi, url: 'https://fastapi.tiangolo.com/', label: 'FastAPI' },
    'rest apis': { icon: FaRegFileCode, url: 'https://restfulapi.net/', label: 'REST APIs' },
    'express': { icon: FaNodeJs, url: 'https://expressjs.com/', label: 'Express' },
    'java': { icon: FaJava, url: 'https://www.java.com/', label: 'Java' },
    'go': { icon: FaRegFileCode, url: 'https://go.dev/', label: 'Go' },
    'bash': { icon: FaLinux, url: 'https://www.gnu.org/software/bash/', label: 'Bash' },
    'sql': { icon: FaDatabase, url: 'https://en.wikipedia.org/wiki/SQL', label: 'SQL' },
    'mysql': { icon: SiMysql, url: 'https://www.mysql.com/', label: 'MySQL' },
    'postgresql': { icon: SiPostgresql, url: 'https://www.postgresql.org/', label: 'PostgreSQL' },
    'mongodb': { icon: SiMongodb, url: 'https://www.mongodb.com/', label: 'MongoDB' },
    'azure': { icon: FaCloud, url: 'https://azure.microsoft.com', label: 'Azure' },
    'power bi': { icon: FaChartBar, url: 'https://powerbi.microsoft.com/', label: 'Power BI' },
    'streamlit': { icon: SiStreamlit, url: 'https://streamlit.io/', label: 'Streamlit' },
    'xgboost': { icon: FaChartBar, url: 'https://xgboost.ai/', label: 'XGBoost' },
    'home assistant': { icon: SiHomeassistant, url: 'https://www.home-assistant.io/', label: 'Home Assistant' },
    'qBittorrent': { icon: SiQbittorrent, url: 'https://www.qbittorrent.org/', label: 'qBittorrent' },
    'qbittorrent': { icon: SiQbittorrent, url: 'https://www.qbittorrent.org/', label: 'qBittorrent' },

    // Container Icons
    'authelia': { icon: FaLock, url: 'https://www.authelia.com/', label: 'Authelia' },
    'redis': { icon: SiRedis, url: 'https://redis.io/', label: 'Redis' },
    'homarr': { icon: FaHome, url: 'https://homarr.dev/', label: 'Homarr' },
    'nginx-proxy-manager': { icon: FaServer, url: 'https://nginxproxymanager.com/', label: 'Nginx Proxy Manager' },
    'theme-park': { icon: FaCloud, url: 'https://theme-park.dev/', label: 'Theme Park' },
    'open-webui': { icon: FaRegFileCode, url: 'https://github.com/open-webui/open-webui', label: 'Open WebUI' },
    'jellyfin': { icon: SiJellyfin, url: 'https://jellyfin.org/', label: 'Jellyfin' },
    'audiobookshelf': { icon: FaBook, url: 'https://www.audiobookshelf.org/', label: 'Audiobookshelf' },
    'nicotine': { icon: FaMusic, url: 'https://nicotine-plus.org/', label: 'Nicotine+' },
    'pihole': { icon: SiPihole, url: 'https://pi-hole.net/', label: 'Pi-hole' },
    'pi-hole': { icon: SiPihole, url: 'https://pi-hole.net/', label: 'Pi-hole' },
    'drupal': { icon: SiDrupal, url: 'https://www.drupal.org/', label: 'Drupal' },
    'portfolio': { icon: FaRegFileCode, url: 'https://nextjs.org/', label: 'Next.js' },
    'lidarr': { icon: SiSonarr, url: 'https://lidarr.audio/', label: 'Lidarr' },
    'vscode': { icon: FaRegFileCode, url: 'https://github.com/coder/code-server', label: 'VS Code Server' },
    'radarr': { icon: SiRadarr, url: 'https://radarr.video/', label: 'Radarr' },
    'sonarr': { icon: SiSonarr, url: 'https://sonarr.tv/', label: 'Sonarr' },
    'navidrome': { icon: FaMusic, url: 'https://www.navidrome.org', label: 'Navidrome' },
    'grafana': { icon: SiGrafana, url: 'https://grafana.com/', label: 'Grafana' },
    'duckdns': { icon: SiDuckduckgo, url: 'https://www.duckdns.org/', label: 'DuckDNS' },
    'nextcloud': { icon: SiNextcloud, url: 'https://nextcloud.com/', label: 'Nextcloud' },
    'mariadb': { icon: SiMariadb, url: 'https://mariadb.org/', label: 'MariaDB' },
    'openai': { icon: SiOpenai, url: 'https://openai.com/', label: 'OpenAI' },
    'home': { icon: FaHome, url: '#', label: 'Home' },
    'tachometer-alt': { icon: FaTachometerAlt, url: '#', label: 'Dashboard' },
    'robot': { icon: FaRobot, url: '#', label: 'Robot' },

    // Social Icons
    'github': { icon: Fa6Github, url: 'https://github.com/jay739', label: 'GitHub' },
    'linkedin': { icon: FaLinkedin, url: 'https://www.linkedin.com/in/jaya-krishna-konda/', label: 'LinkedIn' },
    'twitter': { icon: FaXTwitter, url: 'https://x.com/jay739', label: 'X (Twitter)' },

    // Theme Icons
    'sun': { icon: FaSun, url: '#', label: 'Light Mode' },
    'moon': { icon: FaMoon, url: '#', label: 'Dark Mode' },

    // Default Icon
    'default': { icon: FaRegQuestionCircle, url: '#', label: 'Unknown' },

    // New icons
    'volume-up': { icon: FaVolumeUp, url: '#', label: 'Sound On' },
    'volume-mute': { icon: FaVolumeMute, url: '#', label: 'Sound Off' },
    'book': { icon: FaBook, url: '#', label: 'Book' },
    'music': { icon: FaMusic, url: '#', label: 'Music' }
  };

  const iconData = iconMap[name.toLowerCase()];
  if (!iconData) {
    console.warn(`Icon not found: ${name}`);
    return { icon: FaRegQuestionCircle, url: '#', label: name };
  }
  return iconData;
}

// Dynamic icon component
export function DynamicIcon({ name, className = '', size = 24 }: { name: string, className?: string, size?: number }): JSX.Element {
  const { icon: IconComponent } = getIconData(name);
  return React.createElement(IconComponent, { className, style: { fontSize: size } });
}