services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80"                  # ✅ PUBLIC - for proxy hosts
      - "443:443"                # ✅ PUBLIC - for proxy hosts
      - "127.0.0.1:81:81"        # ✅ LOCALHOST - for proxy host
      - "10.0.0.110:81:81"       # ✅ LOCAL NETWORK - admin interface
      - "100.89.188.84:81:81"    # ✅ TAILSCALE - admin interface
    dns:
      - 172.28.0.1
      - 1.1.1.1
    environment:
      - DISABLE_IPV6=true
      - TP_THEME=dark
      - TP_URL=http://theme-park:80
    volumes:
      - /home/jay739/docker_services/nginx-proxy-manager/data:/data
      - /home/jay739/docker_services/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    networks:
      - proxy_net
      - media_net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:81"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  netdata:
    image: netdata/netdata:latest
    container_name: netdata
    ports:
      - "10.0.0.110:19999:19999"  # ✅ LOCAL NETWORK ACCESS
      - "127.0.0.1:19999:19999"   # ✅ LOCALHOST ACCESS
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./netdata/stream.conf:/etc/netdata/stream.conf:ro
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    restart: unless-stopped
    networks:
      - proxy_net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:19999/api/v1/info"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  portfolio:
    build: 
      context: ./portfolio_site
      dockerfile: Dockerfile
    container_name: portfolio
    ports:
      - "10.0.0.110:3000:3000"  # ✅ LOCAL NETWORK ACCESS
      - "127.0.0.1:3000:3000"   # ✅ LOCALHOST ACCESS
    restart: unless-stopped
    networks:
      - proxy_net
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - OLLAMA_ENDPOINT=http://172.28.0.1:11434
      - OLLAMA_MODEL=llama3:8b
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mariadb:
    image: mariadb:10.7
    container_name: mariadb
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - /home/jay739/docker_services/mariadb/data:/var/lib/mysql
    networks:
      - core_net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=mariadb
    expose:
      - "80"
    volumes:
      - /home/jay739/docker_services/nextcloud/data:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - core_net
      - proxy_net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "10.0.0.110:9000:9000"     # ✅ LOCAL NETWORK ACCESS  
      - "100.89.188.84:9000:9000"  # ✅ TAILSCALE ACCESS
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/jay739/docker_services/portainer/data:/data
    security_opt:
      - no-new-privileges:true
    networks:
      - infra_net
      - proxy_net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:9000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "100.89.188.84:8090:8080"  # ✅ TAILSCALE ACCESS ONLY
    volumes:
      - /home/jay739/docker_services/jenkins/data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /usr/bin/docker:/usr/bin/docker:ro
      - /home/jay739/docker_services:/workspace:ro
    environment:
      - JENKINS_OPTS=--httpPort=8080
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    user: root  # Required for Docker access
    networks:
      - proxy_net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  core_net:
    external: true
  proxy_net:
    external: true
  infra_net:
    external: true
  media_net:
    external: true
