import fs from 'fs';
import path from 'path';
import { Suspense } from 'react';
import GalleryCarousel from '@/components/sections/GalleryCarousel';
import NeuralPageIntro from '@/components/ui/NeuralPageIntro';
import RouteNextSteps from '@/components/layout/RouteNextSteps';

function getInitialGalleryItems() {
  try {
    const manifestPath = path.join(process.cwd(), 'public/images/gallery/manifest.json');
    const raw = fs.readFileSync(manifestPath, 'utf8');
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

export default function GalleryPage() {
  const initialItems = getInitialGalleryItems();

  return (
    <main className="flex min-h-screen flex-col items-center justify-between neural-page-shell gap-4 sm:gap-5">
      <NeuralPageIntro
        title="AI Showcase"
        subtitle="Images generated by Stable Diffusion running on self-hosted Batcave infrastructure — Apple M4 Metal GPU, ComfyUI, all on-premises."
        chips={['Stable Diffusion', 'ComfyUI', 'Apple M4', 'Self-Hosted']}
        theme="gallery"
      />
      <section id="gallery" className="w-full">
        <Suspense fallback={<div className="w-full min-h-[420px] neural-card-soft rounded-xl animate-pulse" />}>
          <GalleryCarousel initialItems={initialItems} />
        </Suspense>
      </section>
      <RouteNextSteps
        items={[
          { href: '/ai-tools?tool=image-generator', label: 'Generate your own', note: 'Open the image generator with shareable presets.' },
          { href: '/homeserver?lite=1', label: 'See the runtime stack', note: 'Inspect the public-safe telemetry behind the visuals.' },
          { href: '/projects?tag=Python', label: 'Explore related projects', note: 'Jump from showcase images into AI systems work.' },
        ]}
      />
    </main>
  );
}
